<?php
return [
    'This e-mail is notification of the following recent change to your {app_name} account' => 'Данное письмо является уведомлением о недавних действиях на сайте {app_name}:',
    'New password requested for account' => 'Для вашего профиля было запрошено восстановление пароля.',
    'Go to reset password link' => 'Для продолжения данной операции перейдите по',
    'address link' => 'ссылке',
    'If you did not make this change or authorize someone else to make the change, contact us immediately' => 'Если вы не совершали данное действие, просто не обращайте внимание на данное письмо.',
    'This email was automatically generated by {app_name}. Please do not reply to this message' => 'Данное письмо было автоматически создано {app_name}. Пожалуйста не отвечайте на него.',
    'Thank you {app_name}' => 'Спасибо, <br> команда {app_name}',
    'New email requested for account' => 'Для вашего профиля была запрошена смена электронной почты.',
    'Go to reset email link' => 'Для продолжения данной операции перейдите по',
    'New car request' => 'Запрос на добавление авто на сайте',
    'Go to' => 'Перейти в',
    'administration' => 'администрирование',
    'New comparison added' => 'Новое сравнение на сайте',
    'User {username} had added new comparison' => 'Пользователь {username} разместил новое сравнение.',
	'New password for account' => 'Новый пароль для учетной записи',
	'Car request approved' => 'Запрос на добавление авто подтвержден',
	'New notification' => 'Оповещение об активности'
];