<?php
/** @var \app\models\CarRequest $model */

?>

<p><?= Yii::t(
		'app/email',
		'This e-mail is notification of the following recent change to your {app_name} account',
		['app_name' => Yii::$app->name]
	); ?></p>

<h4><?= Yii::t('app/email', 'Car request approved'); ?></h4>

<p>
    Марка: <?= $model->manufacturer; ?>
    <br/>
    Модель: <?= $model->model; ?>
</p>

<p>&nbsp;</p>

<p style="font-size: 11px;"><?= Yii::t(
		'app/email',
		'This email was automatically generated by {app_name}. Please do not reply to this message',
		['app_name' => Yii::$app->name]
	);?></p>
