<?php

/** @var \app\models\Notification $model */

use yii\helpers\BaseUrl;
use yii\helpers\Url;

?>

<p><?= Yii::t(
        'app/email',
        'This e-mail is notification of the following recent change to your {app_name} account',
        ['app_name' => Yii::$app->name]
    ); ?></p>

<p>&nbsp;</p>

<p><?= $model->message; ?></p>

<p>&nbsp;</p>

Приятного дня!
<p><?= Yii::t('app/email', 'Thank you {app_name}', ['app_name' => Yii::$app->name]); ?></p>

<p>&nbsp;</p>

<p style="font-size: 11px;"><?= Yii::t(
        'app/email',
        'This email was automatically generated by {app_name}. Please do not reply to this message',
        ['app_name' => Yii::$app->name]
    );?></p>
